    public void close() throws IOException {
      Iterator<PerDocConsumer> it = consumers.iterator();
      IOException err = null;
      while (it.hasNext()) {
        try {
          PerDocConsumer next = it.next();
          if (next != null) {
            next.close();
          }
        } catch (IOException ioe) {
          // keep first IOException we hit but keep
          // closing the rest
          if (err == null) {
            err = ioe;
          }
        }
      }
      if (err != null) {
        throw err;
      }
    }

