    /**
     * Retrieves nested exception.
     */
    public Throwable getException() {
        return cause;
    }

