  @Test
  public void testCreateSnapshotUnexpectedFailuresResultIn500Exception() {
    final Throwable cause = new NullPointerException();
    whenUnexpectedErrorOccursDuringCoreAdminOp(cause);
    
    try {
      CoreAdminOperation.CREATESNAPSHOT_OP.execute(callInfo);
      fail("Expected create-snapshot execution to fail with exception.");
    } catch  (Exception thrown) {
      assertSolrExceptionWithCodeAndCause(thrown, ErrorCode.SERVER_ERROR.code, cause);
    }  
  }

