  @Test
  public void testMaxErrorsDefault() throws IOException {
    // by default the TolerantUpdateProcessor accepts all errors, so this batch should succeed with 10 errors.
    assertAddsSucceedWithErrors("tolerant-chain-max-errors-not-set", docs, null, badIds);
    assertU(commit());
    assertQ(req("q","*:*"),"//result[@numFound='10']");
  }

