  @Test
  public void testRetrieveFromJndiWithCredentials() throws Exception {
    MockInitialContextFactory.bind("java:comp/env/jdbc/JndiDB", dataSource);

    props.put(JdbcDataSource.JNDI_NAME, "java:comp/env/jdbc/JndiDB");
    props.put("user", "Fred");
    props.put("password", "4r3d");
    props.put("holdability", "HOLD_CURSORS_OVER_COMMIT");

    when(dataSource.getConnection("Fred", "4r3d")).thenReturn(
            connection);

    Connection conn = jdbcDataSource.createConnectionFactory(context, props)
            .call();

    verify(connection).setAutoCommit(false);
    verify(connection).setHoldability(1);
    verify(dataSource).getConnection("Fred", "4r3d");

    assertSame("connection", conn, connection);
  }

